server:
  port: 7004
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    instance-id: education-search
    prefer-ip-address: true
spring:
  application:
    name: education-search
  datasource:
    url: jdbc:mysql://localhost:3306/education_demo?characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster‐nodes: 127.0.0.1:9300
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.211.130