server:
  port: 7008
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    instance-id: education-practice
    prefer-ip-address: true
spring:
  application:
    name: education-practice
  datasource:
    url: jdbc:mysql://localhost:3306/education_demo?characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true