server:
  port: 7000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    instance-id: education-user
    prefer-ip-address: true
spring:
  application:
    name: education-user
  datasource:
    url: jdbc:mysql://localhost:3306/education_demo?characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    show-sql: true
  #rabbitmq配置信息
#  rabbitmq:
#    host: 192.168.211.130
jwt:
  config:
    ttl: 36000
    key: education
